### ISSUE TITLE
Fix build dommand in book 

### ISSUE THREAD

**Issue by usama-makhzoum** [LunarLambda/meson-gba#2]
Changing ` meson setup --cross-file=gba.ini build`  to `meson setup --cross-file=meson/gba.ini build`

**Comment by LunarLambda** [comment]
Wrong repository, the book is located at https://github.com/lunarlambda/meson-gba-book

**Comment by LunarLambda** [comment]
Fixed in https://github.com/LunarLambda/meson-gba-book/commit/c7a6391172723a8418c53398957affc474a3b9f8
